"""Bakes a sound pack into RIPPS2.elf: writes RiptOPL's src/ripps2sfxpack.c from a folder of
<event>.adp files (make_sound_pack.py makes one). elf/build.sh runs it when RIPPS2_SOUND_PACK names
such a folder; without it the file stays as the patch series has it, empty, and RIPPS2 plays its
built-in sounds. A SOUND folder beside the ELF still overrides whatever is baked in.

    python elf/theme/tools/bake_sound_pack.py <pack folder> <riptopl>/src/ripps2sfxpack.c

The public build never sets RIPPS2_SOUND_PACK: RIPPS2 itself carries no one else's sounds.
"""
import os
import sys

# sound.h's enum SFX, in order
EVENTS = ['boot', 'cancel', 'confirm', 'cursor', 'message', 'transition', 'bd_connect', 'bd_disconnect',
          'page_in', 'page_out', 'error', 'save', 'launch', 'disc', 'random']


def main():
    pack, out = sys.argv[1], sys.argv[2]
    lines = ['/* Generated by elf/theme/tools/bake_sound_pack.py from a private sound pack. Do not commit. */',
             '#include "include/sound.h"', '']
    ptrs, sizes = [], []
    for i, ev in enumerate(EVENTS):
        path = os.path.join(pack, ev + '.adp')
        if not os.path.isfile(path):
            ptrs.append('0')
            sizes.append('0')
            continue
        data = open(path, 'rb').read()
        if data[:4] != b'APCM':
            sys.exit('%s is not an audsrv ADPCM file' % path)
        name = 'ripps2SfxPack_%s' % ev
        lines.append('static const unsigned char %s[%d] __attribute__((aligned(64))) = {' % (name, len(data)))
        for o in range(0, len(data), 24):
            lines.append('    ' + ', '.join('0x%02x' % b for b in data[o:o + 24]) + ',')
        lines.append('};')
        ptrs.append(name)
        sizes.append(str(len(data)))
        print('baked %-14s %7d bytes' % (ev, len(data)))
    lines.append('const unsigned char *const ripps2SfxPack[SFX_COUNT] = {%s};' % ', '.join(ptrs))
    lines.append('const int ripps2SfxPackSize[SFX_COUNT] = {%s};' % ', '.join(sizes))
    open(out, 'w').write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
